### ISSUE TITLE
preview of "chakra-templates.dev/navigation/navbar" NOT WORKING

### ISSUE THREAD

**Issue by performautodev** [hauptrolle/chakra-templates#128]
Hello,
WOW you make a amazing work keep going 🎉

please fix the chakra-templates.dev/navigation/navbar page:
The preview not working : https://chakra-templates.dev/navigation/navbar  

NOTE: only not working when you open the page at the first time but if you click for example to "Sidebar" then "Sidebar" than return to "Sidebar" will work

**Comment by hauptrolle** [comment]
closed in favor if #198
