### ISSUE TITLE
DesktopNav Chakra-UI Link causes full page refresh

### ISSUE THREAD

**Issue by vmandal** [hauptrolle/chakra-templates#132]
The following causes full page load on clicking nav item url.
```
              <Link
                p={2}
                href={navItem.href ?? '#'}
                fontSize={'sm'}
                fontWeight={500}
                color={linkColor}
                _hover={{
                  textDecoration: 'none',
                  color: linkHoverColor,
                }}>
                {navItem.label}
              </Link>
```

Using Next.js Link component with "as"  solves the full page refresh problem.

`<Link href="/flip" as="/flip" >Flip</Link>
`
But Wrapping Chakra-UI Link with Next.js Link creates conflict with  PopoverTrigger.

**Comment by ronakonline** [comment]
use to instead of href

**Comment by vmandal** [comment]
Something like this does not work 
`<Link to="/flip" >Flip</Link>`

I am trying to implement "With Sub-Navigation & CTA" code mentioned at https://chakra-templates.dev/navigation/navbar

**Comment by hauptrolle** [comment]
> Something like this does not work `<Link to="/flip" >Flip</Link>`
> 
> I am trying to implement "With Sub-Navigation & CTA" code mentioned at https://chakra-templates.dev/navigation/navbar

Have you got it to work now?
Maybe the docs can help:
https://nextjs.org/docs/api-reference/next/link
https://chakra-ui.com/docs/navigation/link

And if you want to combine both, check out this blogpost: 
https://jools.dev/using-nextjs-link-with-chakra-ui-link
