### ISSUE TITLE
Wave effect in Avatar 

### ISSUE THREAD

**Issue by Shiba-Kar** [hauptrolle/chakra-templates#154]
## Optional: Add screenshots, or Figma/Sketch files

![app](https://user-images.githubusercontent.com/24454722/150523288-7dacd2d4-08e0-4187-8b4c-483d0309a716.gif)

**Comment by danish17** [comment]
@hauptrolle, are you working on this? I already have a similar component ready. If you are not working on this, you can assign it to me.

**Comment by hauptrolle** [comment]
> @hauptrolle, are you working on this? I already have a similar component ready. If you are not working on this, you can assign it to me.

Feel free to work on that @danish17 😊
