### ISSUE TITLE
collapse-state-when-drawer-opens-and-closes

### ISSUE THREAD

**Issue by thebinario** [hauptrolle/chakra-templates#155]
Very nice work guys. THKS

## Optional: Add screenshots, or Figma/Sketch files
![image](https://user-images.githubusercontent.com/46110587/150701844-7e86f9b2-3817-4b0c-bc9a-d5a4c2fbd560.png)
![image](https://user-images.githubusercontent.com/46110587/150701851-800341bf-9f52-4dc5-b414-e2357661445c.png)

**Comment by TawalMc** [comment]
Hi. Want to work on this feature.

**Comment by TawalMc** [comment]
> Very nice work guys. THKS
> 
> ## I need for my project with this drawer. I have a button, when clicking this it only show just icons, hidding other informations.
> ## Optional: Add screenshots, or Figma/Sketch files
> ![image](https://user-images.githubusercontent.com/46110587/150701844-7e86f9b2-3817-4b0c-bc9a-d5a4c2fbd560.png) ![image](https://user-images.githubusercontent.com/46110587/150701851-800341bf-9f52-4dc5-b414-e2357661445c.png)

So initially (basic state) the drawer is displayed and only icons are visible and after the click on menu button icon descriptions are displayed then ?

**Comment by TawalMc** [comment]
I started working on this feature

**Comment by TawalMc** [comment]
I push a commit where I re-create the collapse sidebar with tooltip, you can check [online here](https://chakra-templates-git-fork-tawalmc-collapse-sidebar-hauptrolle.vercel.app/navigation/sidebar)

**Comment by hauptrolle** [comment]
Closed because of inactivity.
