### ISSUE TITLE
Buttons components

### ISSUE THREAD

**Issue by TawalMc** [hauptrolle/chakra-templates#159]
# Feature request
Build button template like other template on the page

## Describe the feature you need
I want to ask if It is possible to extract from [https://chakra-templates.dev/components/cards](https://chakra-templates.dev/components/cards) page, the buttons used like: follow button or start your trial and make them like template component so user can copy easily their code and use them.
I can work on the extraction of codes and do more by building some buttons but I don't know if it follow the goal of the project to have more complete template.
Thanks

**Comment by hauptrolle** [comment]
Hey @TawalMc, we no also have a `Buttons` category. So feel free to go ahead an extract the buttons into that category. I am looking forward to a PR from you :)

**Comment by TawalMc** [comment]
Right😎

**Comment by TawalMc** [comment]
Hi i've made a pull request where I add two buttons.

**Comment by hauptrolle** [comment]
Thank you for your work! Closed with #166
