### ISSUE TITLE
E learning template

### ISSUE THREAD

**Issue by dilipkk-foyernet** [hauptrolle/chakra-templates#165]
# Template request
E Learning for school
## Describe the template you need
We need following sections Course list, course details, Lessons list, lesson summary, Instructors
## Additional information
Reference: https://zone-ui.vercel.app/e-learning/

**Comment by danish17** [comment]
IMO, these templates will be too specific. We want to create templates which have a general utility to them, like buttons and hero sections. Is it possible to generalize the components/templates which you wish to see?

**Comment by koladilip** [comment]
Can you make some templates with dynamic form fields like adding multiples of the same element like form with multiple addresses etc?

**Comment by danish17** [comment]
> Can you make some templates with dynamic form fields like adding multiples of the same element like form with multiple addresses etc?

I think we can create some generic lists, tables, and cards. You can possibly use them as per your needs.
