### ISSUE TITLE
Client side error when using the Hyper Theme Editor

### ISSUE THREAD

**Issue by pmnord** [hauptrolle/chakra-templates#175]
When adding a new brand color and clicking on the grid of shades.
![Screenshot from 2022-04-26 13-40-48](https://user-images.githubusercontent.com/14935197/165388756-a521d4c4-6ee0-49c7-8e6e-942f4e2ce97c.png)

**Comment by hauptrolle** [comment]
Will probably remove the hyper theme editor in the next release, because it will use sandpack for displaying the tempaltes.
