### ISSUE TITLE
Multi-step form Template

### ISSUE THREAD

**Issue by Prasanna0908** [hauptrolle/chakra-templates#187]
# Template request
Multi-step form Template

## Describe the template you need
I have been using chakra templates for more than a year now and I really appreciate the community for providing awesome templates :)
But currently, multi-step form template is missing

## Additional information
I already have multi-step form created in chakra UI 

## Optional: Add screenshots, or Figma/Sketch files
![Multi step form](https://user-images.githubusercontent.com/65851817/176829540-271a97c9-4c4e-4a83-9f6d-42685dcccdb2.PNG)

Can @hauptrolle or any of the project admins assign me this issue?

**Comment by hauptrolle** [comment]
Hey @Prasanna0908 I am looking forward to your PR :)

**Comment by Prasanna0908** [comment]
Hey, @hauptrolle, I have created a pull request. Let me know if any changes are required

**Comment by ekhiw** [comment]
@hauptrolle hi, when this template merged? this is very useful form

**Comment by ekhiw** [comment]
@hauptrolle @Prasanna0908  I think this issue can be closed now

**Comment by Prasanna0908** [comment]
Sure, @ekhiw. Thanks, again!
