### ISSUE TITLE
New template for Features sections

### ISSUE THREAD

**Issue by AshutoshDash1999** [hauptrolle/chakra-templates#208]
# Template request
Features section template

## Describe the template you need
A fresh design for the Features section

## Optional: Add screenshots, or Figma/Sketch files
![got this from behance](https://user-images.githubusercontent.com/46455250/194763867-ef310e23-21fd-4aef-82c3-d6a0a0d02c23.png)

**Comment by Prasanna0908** [comment]
Hey @hauptrolle Can you assign me this issue?

**Comment by hauptrolle** [comment]
Closed because of inactivity.
