### ISSUE TITLE
Bug Report Template

### ISSUE THREAD

**Issue by Utkarshn10** [hauptrolle/chakra-templates#213]
# Feature request
Add a Bug Report Template.

## Describe the feature you need
Addition of a bug report template, so that it becomes easier for contributors to report bugs.

## Additional information

You can refer [this](https://gist.github.com/automationhacks/87b62440faf36d98ebbb732c372dd7c3).

**Comment by Utkarshn10** [comment]
Hey @hauptrolle I would like to work on this issue.

**Doubt:**  are we looking to add the same template mentioned above or there are any required changes that you would like to add.

**Comment by hauptrolle** [comment]
@Utkarshn10 That looks good. Feel free to add it 👍

**Comment by Utkarshn10** [comment]
@hauptrolle i have created the PR :)
