### ISSUE TITLE
Update the number of contributors

### ISSUE THREAD

**Issue by Utkarshn10** [hauptrolle/chakra-templates#216]
The data regarding the number of contributors is outdated. Update the number of contributors on the homepage

# Screenshot
![Screenshot (150)](https://user-images.githubusercontent.com/58587256/198507489-8d7d4fb7-7030-4269-98bb-31587a58f62d.png)

**Comment by hauptrolle** [comment]
If we fix #219 this should be solved aswell.

**Comment by hauptrolle** [comment]
Done :)
