### ISSUE TITLE
Update the contributor's list on Homepage

### ISSUE THREAD

**Issue by Utkarshn10** [hauptrolle/chakra-templates#218]
The contributor's list on homepage of chakra-templates is outdated. It has 32 contributors while the project now has 41 contributors.

# Screenshot
![Screenshot (152)](https://user-images.githubusercontent.com/58587256/198508190-8799c7c2-50e1-43d7-91d5-9ed282331e7e.png)

**Comment by hauptrolle** [comment]
The list is fetched from the .all-contributors.rc Should be fixed now. (The Site is build with Next.js and ISR. So it might take a while to display new contributors)
