### ISSUE TITLE
Update the contributor's list in Readme

### ISSUE THREAD

**Issue by Utkarshn10** [hauptrolle/chakra-templates#219]
The contributor's list in readme of chakra-templates is outdated. It has 32 contributors while the project now has 41 contributors.

**Comment by hauptrolle** [comment]
@all-contributors please add @mohamedsamara for code

**Comment by hauptrolle** [comment]
@all-contributors please add @Prasanna0908 for code

**Comment by hauptrolle** [comment]
@all-contributors please add @Utkarshn10 for docs

**Comment by hauptrolle** [comment]
@all-contributors please add @ekhiw for doc

**Comment by hauptrolle** [comment]
@all-contributors please add @PatelN123 for code

**Comment by hauptrolle** [comment]
https://github.com/all-contributors please add @Harsh2220 for code

**Comment by hauptrolle** [comment]
@all-contributors please add @Harsh2220 for code

**Comment by hauptrolle** [comment]
@all-contributors please add @JakovGlavac for code

**Comment by hauptrolle** [comment]
@all-contributors please add @1129-tame for docs

**Comment by hauptrolle** [comment]
@all-contributors please add @devdev-dev for docs

**Comment by hauptrolle** [comment]
@all-contributors please add @benyou1969 for docs

**Comment by hauptrolle** [comment]
@all-contributors please add @MadhuSaini22 for doc

**Comment by hauptrolle** [comment]
List is now complete again.
