### ISSUE TITLE
Accessibility issues with some templates

### ISSUE THREAD

**Issue by Zwyx** [hauptrolle/chakra-templates#245]
Hi and congrats for making these beautiful templates.

Some of them though, are not accessible. For example:

- https://chakra-templates.dev/templates/navigation/navbar/withSubnavigation

On this one, the Tab key should move from one element to the other, then the Space or Enter keys should open the sub navigation menu, then the arrows keys should allow navigating the menu, the Escape key should allow closing the menu, and the Space or Enter key should allow selecting an item.

- https://chakra-templates.dev/templates/navigation/sidebar/simpleSidebar

On this one, no clue is given about which element is selected when using the Tab key.

**Comment by hauptrolle** [comment]
Hey @Zwyx thank you for your kind words.

Good catch there with the accessibility issues 👌 
I am am still planning if and how I can restructure the whole project. The accessibility will be definitely a part of it.

If you want, you can also open a MR to fix these issues.
