### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by fernandounger** [hauptrolle/chakra-templates#272]
# Feature request

I created a simple yet elegant accordion component that offers expandable sections with a smooth and clean transition. Furthermore, the component is highly customizable, allowing you to adjust colors, sizes and other properties.

## Describe the feature you need

I would like to request a review of my pull request [#270] for the addition of a simple accordion component to the project.

**Comment by hauptrolle** [comment]
Merged. Thanks for your contribution! 👍
