### ISSUE TITLE
Make chakra-templates.dev a PWA so it can be installed and used offline

### ISSUE THREAD

**Issue by lazarnikolov94** [hauptrolle/chakra-templates#29]

**Comment by hauptrolle** [comment]
Is that really a use case? Are people doing web development offline? 😁

**Comment by lazarnikolov94** [comment]
Not necessarily offline, but maybe an installable would be cool. This has the lowest priority ever 😂

**Comment by hauptrolle** [comment]
Will close this for now. Maybe we will add this feature later 😄
