### ISSUE TITLE
Cannot copy code from last Navbar template

### ISSUE THREAD

**Issue by testacode** [hauptrolle/chakra-templates#299]
Hi there, I'm not being able to copy it directly from the page. I had to take a snapshot and run some OCR to get the code. Is that the inteded way or is it any other simple way. Also I see that the NavLink component inside the last Navbar code is just sitting there without being used.

**Comment by Hexvortex** [comment]
Yeah facing same issue

**Comment by hauptrolle** [comment]
Fixed.
