### ISSUE TITLE
Copy from examples is broken

### ISSUE THREAD

**Issue by tonyjara** [hauptrolle/chakra-templates#313]
Hi guys, I can't see the copy codeblock button or select from the code block in the examples anymore. I'll try to submit a pr tomorrow if I can figure out what's wrong but meanwhile I just wanted to report it. Have a good one.

**Comment by Hexvortex** [comment]
Hi @tonyjara  
I was also facing same issue ,i have fixed  issue and given  pull request #307.But i didnt get why my PR is failing at versel.

you can check https://github.com/hauptrolle/chakra-templates/pull/307 for detailed problem description and solution.

Just want to know why my PR is failing ,if you can suggest it would be great.

**Comment by tonyjara** [comment]
@Hexvortex  Thank you for that! Sadly I don't have access to see the deployment errors. Did it build ok whenever you tried it on your computer? I'm going to try your fix now.

**Comment by tonyjara** [comment]
@Hexvortex I tried your fix and added something on top of it to fix the line selection not working. It think yours didn't build because of prettier errors. It was set to error on the .eslint file.
