### ISSUE TITLE
Templates: Grid with blurred backdrop

### ISSUE THREAD

**Issue by lazarnikolov94** [hauptrolle/chakra-templates#40]
# Grid with blurred backdrop
- Designed with 1920 width
- Container: 2 columns centered, 640px each
- Caption font: Work Sans Bold 20px *uppercased*
- Title font: Work Sans Bold 48px
- Description font: Inter Medium 16px
- Testimonial font: Inter Medium 14px
- Client name font: Work Sans Bold 14px
- Client profession font: Inter Medium 14px
- Client photo size: `80px` width x `80px` height
- Purple: Chakra's `purple.400` or `#9F7AEA` in HEX
- Backdrop blur: `~40px`
- [Download assets](https://github.com/hauptrolle/chakra-templates/files/5826846/assets.zip)

![Grid with avatars](https://user-images.githubusercontent.com/5396211/104856102-e9b16d00-5910-11eb-8393-0c70641f655d.png)

**Comment by AndreaBarghigiani** [comment]
There is an ETA for this one? I would like to start my contributions with this 😊

**Comment by hauptrolle** [comment]
I just assigned that to you. So just take your time 😀

**Comment by hauptrolle** [comment]
Hey @AndreaBarghigiani how its going? Any updates regarding the template? 😀

**Comment by AndreaBarghigiani** [comment]
You're right sir, last week was a crazy one full of work. I am trying to do it in this one 😉 
Thanks for checking out.

**Comment by hauptrolle** [comment]
In the meantime we have added a [Testimonials Section](https://chakra-templates.dev/page-sections/testimonials) where this could fit in.

Any new updates when you can add this template? 🙈  Do you need some help, or still under heavy work load?
