### ISSUE TITLE
Analytics: Measure "Copy" button clicks

### ISSUE THREAD

**Issue by lazarnikolov94** [hauptrolle/chakra-templates#42]
Add an event to measure the "Copy" button clicks. If possible, it'd be good if the "Manual Select & Copy" can be measured as well.

**Comment by yurywektorovich** [comment]
And where to store this data?

@lazarnikolov94

**Comment by lazarnikolov94** [comment]
> And where to store this data?
> 
> 
> 
> @lazarnikolov94 

In splitbee itself. We already have an integration. Maybe this task is better suited for @hauptrolle since only he has access to the Splitbee account 😂

**Comment by yurywektorovich** [comment]
Okay. Thanks for the quick answer)

**Comment by hauptrolle** [comment]
> > And where to store this data?
> > @lazarnikolov94
> 
> In splitbee itself. We already have an integration. Maybe this task is better suited for @hauptrolle since only he has access to the Splitbee account 😂

Yeah, currenty I am the only one with access to the splitbee account. Sorry for that 🙈 

But adding tracking to that button should be pretty easy. We can just add an `data-splitbee-event` attribute to that button.

I am not sure if we can track that manual copy somehow ...

**Comment by hauptrolle** [comment]
We are also thinking about switching to Google Analytics.
