### ISSUE TITLE
Bug: Header issues on LinkedIn built-in browser

### ISSUE THREAD

**Issue by lazarnikolov94** [hauptrolle/chakra-templates#46]
Opening the Templates page in LinkedIn's built-in browser causes rendering issues in the Header component. This happens on iOS devices with a notch, so I suspect it's the `safe-area` property.

![image](https://user-images.githubusercontent.com/5396211/105045658-6f93fc00-5a68-11eb-9aa8-0a191df917f5.png)

**Comment by hauptrolle** [comment]
LinkedIn 🤷‍♂️
