### ISSUE TITLE
Blog Article List

### ISSUE THREAD

**Issue by igeligel** [hauptrolle/chakra-templates#62]
# Template request

A blog article list.

## Describe the template you need

Pictures say more than 1000 words

![localhost_3000_blog (3)](https://user-images.githubusercontent.com/12736734/110223936-bf733900-7ed7-11eb-861f-f8378fa557ce.png)

Something like this. What do you think?

## Additional information

I can implement this if you want. I got it implemented already on a page and would like to share it.

## Optional: Add screenshots, or Figma/Sketch files

![localhost_3000_blog (3)](https://user-images.githubusercontent.com/12736734/110223936-bf733900-7ed7-11eb-861f-f8378fa557ce.png)

**Comment by hauptrolle** [comment]
Hey @igeligel 👋 

That looks cool!
Feel free to open a PR and contribute these as a template. Let me know if you need any asisstance :)

**Comment by hauptrolle** [comment]
Hey @igeligel Any updates regarding this template? Do you still want to contribute it? Would love to see it 😃

**Comment by igeligel** [comment]
Hey @hauptrolle, yes will try to contribute it this week. Got caught up with some other projects recently.

**Comment by hauptrolle** [comment]
@igeligel Cool! Feel free to ping me if you need some support :v:
