### ISSUE TITLE
Component request: Progress Steps

### ISSUE THREAD

**Issue by laubonghaudoi** [hauptrolle/chakra-templates#73]
# Template request

## Describe the template you need

I need a vertical steps component, which is exactly the same as this one: https://pro.chakra-ui.com/components/application-ui/steps

## Optional: Add screenshots, or Figma/Sketch files

![image](https://user-images.githubusercontent.com/11172180/116773730-10049f80-aa0c-11eb-8fc1-41a63ae36b3d.png)

**Comment by kotoyama** [comment]
hello, [look at this](https://github.com/jeanverster/chakra-ui-steps)

**Comment by laubonghaudoi** [comment]
@kotoyama Wow, thank you so much! I will keep this issue open until they add this to their list officially.

**Comment by hauptrolle** [comment]
I think chakra-templates is not the place to build new chakra components. I will close this.
