### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by MarkSFrancis** [hauptrolle/chakra-templates#74]
What license is the code under? 

Obviously, there's the "Copy the code" section on the home page, but it might be worth adding a license to this repository (like the [UNLICENSE](https://unlicense.org/)) to be more explicit about the copying terms.

It may also be worth considering if you want the code samples to be under a different license than the website itself, but that's up to you - the maintainer(s)

**Comment by hauptrolle** [comment]
Hey @MarkSFrancis thanks for raising that topic. I have added MIT licence now.  👌
