### ISSUE TITLE
Bug: useColorModeValue in Navbar

### ISSUE THREAD

**Issue by itisparas** [hauptrolle/chakra-templates#82]
Error:  `React Hook "useColorModeValue" cannot be called inside a callback.`

Template: `Navbar`

How to reproduce?
I created a react-app using `create-react-app --template typescript` installed all the Chakra UI dependencies using yarn.

I copied the code from Chakra templates dev website and put it in a separate .tsx file.

When I am using that component using `<WithSubnavigation />` I see an error `React Hook "useColorModeValue" cannot be called inside a callback.` in DesktopNav function.

**Comment by llermaly** [comment]
Same here :(

**Comment by Ningaro** [comment]
+1

**Comment by hauptrolle** [comment]
Hey guys, sorry for answering this late. I am probably gonna fix that issue this week!
